### PR TITLE
Prefer PHPCS and dependencies from current directory

### PR DESCRIPTION
**Pull request by lcobucci**
Avoiding version mismatch issues...

This might be a little naive but should work fine...

### CODE REVIEW

**Comment by morozov** [comment]
It should be already fixed in https://github.com/diff-sniffer/core/issues/8. At least it works for me with doctrine/dbal. Please try using the version from Git, not PHAR. I can release it later once you confirm it works.

**Comment by lcobucci** [comment]
@morozov I was using the version from `git` but that change you made didn't get deployed and this package is depending on the stable version: https://github.com/diff-sniffer/git/blob/96a3c264f154a9a5b6e62084427ab7ce39df184e/composer.json#L12

I'm happy to trash this once things get updated, though :)

**Comment by morozov** [comment]
@lcobucci please check [release 0.3.1](https://github.com/diff-sniffer/git/releases/tag/0.3.1).

**Comment by lcobucci** [comment]
@morozov works like a charm, thanks a lot!

**Pull request closed without merging**
